trigger:
  branches:
    include: [main]

variables:
  azureServiceConnection: "sc-azure-spn" # <-- your service connection name
  webAppName: "mywebapp22" # <-- your App Service name
  publishFolder: "$(Build.ArtifactStagingDirectory)/publish"
  packagePath: "$(Build.ArtifactStagingDirectory)/webapp.zip"
  vmImage: "ubuntu-latest"

pool:
  vmImage: $(vmImage)

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "8.0.x"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(publishFolder)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(packagePath)"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployWeb
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  displayName: "Deploy to App Service"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    appName: "$(webAppName)"
                    # For Windows App Service, use 'webApp'; for Linux, use 'webAppLinux'
                    appType: "webAppLinux"
                    package: "$(Pipeline.Workspace)/drop/webapp.zip"
